### ISSUE TITLE
Strength stored as intager

### ISSUE THREAD

**Issue by Mabeeck** [quaris628/EinsteinEditor#7]
I've just noticed that in v1.4.1, every time I have a synapse with a strength of 0.2, upon saving/loading it gets converted to 2.
This works with other values too, for example, 2.5, which is converted to 25.

**Comment by quaris628** [comment]
What region/culture is your computer in? Something non-US-english?
I assume this would have something to do with it, because my PC can load and save decimal values fine, and this isn't the first time someone has had weird bugs with converting text to decimal numbers and vice versa.
I might just have to write my own text to float number converter to fix this, which would be fairly tedious.

**Comment by quaris628** [comment]
If you're even checking back: Can you tell me if this version has the issue fixed?
[EinsteinEditor-dev-float-parsing-rewrite.zip](https://github.com/quaris628/EinsteinEditor/files/13767276/EinsteinEditor-dev-float-parsing-rewrite.zip)

**Comment by Mabeeck** [comment]
Sorry for the late reply, yes that version seems to have the issue fixed and my region is Germany.
