### ISSUE TITLE
err

### ISSUE THREAD

**Issue by Thesailmustbeweakened** [quaris628/EinsteinEditor#9]
---------------- Technical Details ----------------
Name: FileNotFoundException
Message: ../res/ButtonBackground.png
Target Site: System.Drawing.Image FromFile(System.String, Boolean)
Stack Trace:
   在 System.Drawing.Image.FromFile(String filename, Boolean useEmbeddedColorManagement)
   在 Einstein.ui.menu.NeuronMenuButton..ctor(Int32 x, Int32 y, String text, Action onSelect, Action onDeselect)
   在 Einstein.EditorScene..ctor(Scene prevScene)
   在 Einstein.EinsteinMain.Main()

---------------- Einstein Data State ----------------

 ---------------- phi.IO ----------------

FrameTimerInputHandler
frameActions:
lockedFrameActions:
uninitActions:

KeyInputHandler
todos:
MOUSE.CLICK:
actions:
todos:
MOUSE.CLICK:
actions:
todos:
MOUSE.RIGHT_CLICK:
actions:
todos:
MOUSE.MID_CLICK:
actions:
todos:
MOUSE.DOWN:
actions:
todos:
MOUSE.LEFT_DOWN:
actions:
todos:
MOUSE.RIGHT_DOWN:
actions:
todos:
MOUSE.MID_CLICK_DOWN:
actions:
todos:
MOUSE.UP:
actions:
todos:
MOUSE.LEFT_UP:
actions:
todos:
MOUSE.RIGHT_UP:
actions:
todos:
MOUSE.MID_CLICK_UP:
actions:
todos:
MOUSE.MOVE:
actions:
todos:

**Comment by quaris628** [comment]
Thanks for your report!

The issue is:
The BackgroundButton.png file cannot be found. All files in the /bin/ and /res/ folders need to remain in their original locations. If you move a file, an error will happen.

To resolve this issue:
Move the files to where they started. The easiest way is to re-extract the files from the .zip again.

**Comment by quaris628** [comment]
Closing given there's no response after 6 months.
